/* =========================================================
 * data.js — 内置雅思词库（场景分类）+ 每日一句
 * 全部为公开领域常识性词条与自撰例句，不抓取受版权保护的词典网页。
 * 词条结构（紧凑数组，由 app.js 解析成对象）：
 *  0 word        单词
 *  1 phonetic    音标
 *  2 pos         词性
 *  3 meaningCN   中文释义
 *  4 meaningEN   英文释义
 *  5 exampleEN   例句（英文）
 *  6 exampleCN   例句（中文）
 *  7 category    场景分类 id
 *  8 tags        标签（用 / 分隔）
 *  9 roots       词根词缀
 * 10 synonyms    同义替换（用 ; 分隔）
 * 11 collocations常见搭配（用 ; 分隔）
 * 12 ieltsUsage  雅思写作/口语关联
 * 13 difficulty  难度 1基础 2进阶 3高阶
 * ========================================================= */

var CATEGORIES = [
  { id:'education',   name:'教育' }, { id:'environment', name:'环境' },
  { id:'technology',  name:'科技' }, { id:'health',      name:'健康' },
  { id:'work',        name:'工作' }, { id:'travel',      name:'旅游' },
  { id:'culture',     name:'文化' }, { id:'society',     name:'社会' },
  { id:'law',         name:'法律' }, { id:'media',       name:'媒体' },
  { id:'economy',     name:'经济' }, { id:'government',  name:'政府' },
  { id:'crime',       name:'犯罪' }, { id:'transport',   name:'交通' },
  { id:'city',        name:'城市' }, { id:'rural',       name:'乡村' },
  { id:'art',         name:'艺术' }, { id:'sport',       name:'体育' },
  { id:'family',      name:'家庭' }, { id:'food',        name:'食物' }
];

var DAILY_SENTENCES = [
  ['Consistent daily practice matters more than occasional intensive study.','每天坚持练习，比偶尔突击学习更重要。'],
  ['Vocabulary is the building block of fluent expression.','词汇是流利表达的基础。'],
  [' Governments should invest in renewable energy to curb carbon emissions.','政府应投资可再生能源以抑制碳排放。'],
  ['Technology has reshaped the way people communicate and work.','科技重塑了人们沟通与工作的方式。'],
  ['A balanced diet and regular exercise reduce the risk of chronic illness.','均衡饮食与规律运动可以降低慢性病风险。'],
  ['Urbanisation brings both opportunities and pressures to city dwellers.','城市化给城市居民带来机遇，也带来压力。'],
  ['Education is widely regarded as a key driver of social mobility.','教育被广泛视为社会流动的关键驱动力。'],
  ['The media plays a powerful role in shaping public opinion.','媒体在塑造公众舆论方面作用强大。'],
  ['Economic growth should not come at the expense of the environment.','经济增长不应以环境为代价。'],
  ['Stricter legislation can deter potential offenders.','更严格的立法可以震慑潜在违法者。'],
  ['Public transport helps ease traffic congestion in large cities.','公共交通有助于缓解大城市的交通拥堵。'],
  ['Cultural heritage deserves protection for future generations.','文化遗产值得为后代加以保护。'],
  ['Flexible working arrangements improve employees wellbeing.','弹性工作安排能提升员工的幸福感。'],
  ['Tourism can boost the local economy but may damage ecosystems.','旅游业能拉动地方经济，但也可能破坏生态系统。'],
  ['Childrens upbringing is shaped by both family and school.','孩子的成长既受家庭影响，也受学校影响。'],
  ['Art encourages people to see the world from a new angle.','艺术鼓励人们从新的角度看待世界。'],
  ['Sport teaches teamwork, discipline and resilience.','体育教会人团队合作、自律与韧性。'],
  ['Food security remains a pressing issue in many regions.','粮食安全在许多地区仍是紧迫问题。'],
  ['Rural depopulation has become a concern for policymakers.','乡村人口流失已成为政策制定者关注的问题。'],
  ['Reliable data is essential for sound decision-making.','可靠的数据对合理决策至关重要。']
];

var RAW_WORDS = [
/* ---------------- 教育 education ---------------- */
["curriculum","/kəˈrɪkjələm/","n.","课程；教学大纲","all the subjects taught in a school or course","The school revised its curriculum to include coding classes.","学校修订了课程，加入了编程课。","education","教育/课程/学校","curr(=run 跑)+iculum→教学进程","syllabus; coursework; programme","broad curriculum; school curriculum; curriculum design","写作教育类高频：a broad/balanced curriculum；口语 Part1 studies 可替换 subjects",2],
["pedagogy","/ˈpedəɡɒdʒi/","n.","教学法；教育学","the theory and practice of teaching","Modern pedagogy emphasises active learning rather than rote memorisation.","现代教学法强调主动学习而非死记硬背。","education","教育/教学/理论","ped(=child 儿童)+agog(=lead 引导)","teaching method; instruction; didactics","traditional pedagogy; teaching pedagogy; pedagogy training","写作：teaching methods 的学术替换词",3],
["literacy","/ˈlɪtərəsi/","n.","读写能力；素养","the ability to read and write; competence in an area","Digital literacy is now as important as basic literacy.","数字素养如今和基础读写能力一样重要。","education","教育/能力/基础","liter(=letter 字母)+acy(名词后缀)","reading ability; competence; proficiency","literacy rate; digital literacy; financial literacy","写作：literacy rate 常用于图表题与教育类论证",2],
["enrolment","/ɪnˈrəʊlmənt/","n.","注册人数；入学","the act of enrolling or the number of people enrolled","University enrolment has risen steadily over the past decade.","过去十年大学入学人数稳步上升。","education","教育/招生/数据","en-(使)+roll(名单)+ment","registration; intake; admission","student enrolment; enrolment rate; enrolment figures","图表题常用：enrolment figures / student intake",2],
["tuition","/tjuˈɪʃn/","n.","学费；（一对一）教学","the fee for instruction; individual teaching","Rising tuition fees make higher education unaffordable for some families.","学费上涨使一些家庭负担不起高等教育。","education","教育/费用/学习","tuit(=guard 看护)+ion","fee; schooling; instruction","tuition fees; private tuition; tuition costs","写作：tuition fees 是教育公平话题核心搭配",2],
["academic","/ˌækəˈdemɪk/","adj./n.","学术的；大学教师","related to education and study; a university teacher","Academic pressure can affect students' mental health.","学业压力会影响学生的心理健康。","education","教育/学术/学校","academ(=Academy 学院)+ic","scholastic; educational; scholarly","academic performance; academic pressure; academic year","写作：academic performance/qualification；口语常用 academic pressure",1],
["compulsory","/kəmˈpʌlsəri/","adj.","义务的；必修的","required by law or rules","Compulsory education lasts nine years in many countries.","许多国家的义务教育为九年。","education","教育/法律/义务","com-+puls(=drive 驱使)+ory","mandatory; obligatory; required","compulsory education; compulsory subject; compulsory attendance","写作：compulsory vs optional 对比论证常用",2],
["vocational","/vəʊˈkeɪʃənl/","adj.","职业的；职业培训的","preparing people for a particular job or trade","Vocational training offers a practical alternative to university.","职业培训提供了上大学之外的实用选择。","education","教育/职业/培训","voc(=call 召唤)+ation+al","professional; occupational; technical","vocational training; vocational course; vocational skills","写作教育/就业话题：vocational training vs academic education",2],
["scholarship","/ˈskɒləʃɪp/","n.","奖学金；学问","money awarded to study; academic achievement","She won a scholarship to study environmental science.","她获得了奖学金去读环境科学。","education","教育/奖励/学术","schol(=school/learn)+ar+ship","grant; bursary; award","win a scholarship; scholarship programme; full scholarship","写作：government-funded scholarships 用于教育公平论证",1],
["dropout","/ˈdrɒpaʊt/","n.","辍学者；辍学","someone who leaves school or a course early","The dropout rate is higher in rural areas than in cities.","农村地区的辍学率高于城市。","education","教育/问题/数据","drop+out（脱离）","school leaver; early leaver","dropout rate; school dropout; reduce dropout","图表/写作：dropout rate 是教育类常见数据表达",2],

/* ---------------- 环境 environment ---------------- */
["biodiversity","/ˌbaɪəʊdaɪˈvɜːsəti/","n.","生物多样性","the variety of plant and animal life in a place","Deforestation poses a serious threat to biodiversity.","森林砍伐对生物多样性构成严重威胁。","environment","环境/生态/科学","bio(=life 生命)+diversity(多样性)","variety of species; ecological variety","loss of biodiversity; protect biodiversity; biodiversity hotspot","写作环境类：loss of biodiversity / preserve biodiversity",3],
["emission","/ɪˈmɪʃn/","n.","排放（物）","the release of gas, heat or light into the air","Governments should tax carbon emissions to slow climate change.","政府应对碳排放征税以减缓气候变化。","environment","环境/污染/政策","e-(出)+miss(=send 送)+ion","discharge; release; output","carbon emissions; emission targets; cut emissions","写作必背：cut/reduce carbon emissions；emission targets",2],
["sustainable","/səˈsteɪnəbl/","adj.","可持续的","able to be maintained without harming the environment","Cities need sustainable transport to cut pollution.","城市需要可持续的交通来减少污染。","environment","环境/发展/政策","sus-(下)+tain(=hold 保持)+able","eco-friendly; viable; long-term","sustainable development; sustainable growth; sustainable energy","写作：sustainable development 是万能高分搭配",2],
["deforestation","/ˌdiːˌfɒrɪˈsteɪʃn/","n.","森林砍伐","the clearing of forests by cutting or burning trees","Large-scale deforestation has destroyed many natural habitats.","大规模森林砍伐摧毁了许多自然栖息地。","environment","环境/破坏/生态","de-(去除)+forest+ation","logging; clearing; forest loss","deforestation rate; widespread deforestation; combat deforestation","写作：deforestation 与 habitat loss 常连用",3],
["conservation","/ˌkɒnsəˈveɪʃn/","n.","保护；保存","the protection of nature or resources","Water conservation should be part of every household routine.","节水应当成为每个家庭的日常习惯。","environment","环境/保护/资源","con-+serv(=keep 保存)+ation","preservation; protection; safeguarding","wildlife conservation; energy conservation; conservation area","写作：wildlife/energy conservation；动词 conserve 同用",2],
["ecosystem","/ˈiːkəʊsɪstəm/","n.","生态系统","a community of living things and their environment","Plastic waste damages the marine ecosystem.","塑料废弃物破坏海洋生态系统。","environment","环境/生态/科学","eco(=house 家)+system(系统)","ecological community; habitat; biosphere","marine ecosystem; fragile ecosystem; disrupt the ecosystem","写作：fragile ecosystem / disrupt the ecosystem",2],
["renewable","/rɪˈnjuːəbl/","adj.","可再生的","able to be replaced naturally; not used up","Investment in renewable energy has grown rapidly.","对可再生能源的投资迅速增长。","environment","环境/能源/政策","re-(再)+new+able","sustainable; inexhaustible; green","renewable energy; renewable resources; renewable sources","写作能源话题：renewable energy sources（solar, wind）",2],
["mitigate","/ˈmɪtɪɡeɪt/","v.","减轻；缓解","to make something bad less severe","Planting trees can mitigate the effects of urban heat.","植树可以缓解城市热岛效应。","environment","环境/解决/动词","mit(=mild 温和)+igate(使)","alleviate; ease; reduce","mitigate the impact; mitigate climate change; mitigate risks","写作高分动词：mitigate the impact/effects of…",3],
["degradation","/ˌdeɡrəˈdeɪʃn/","n.","退化；恶化","the process of becoming worse in quality","Soil degradation threatens long-term food production.","土壤退化威胁长期粮食生产。","environment","环境/问题/农业","de-(向下)+grad(=step 走)+ation","deterioration; decline; degeneration","environmental degradation; land degradation; soil degradation","写作：environmental degradation 常用作论点主语",3],
["habitat","/ˈhæbɪtæt/","n.","栖息地","the natural home of a plant or animal","Urban expansion has destroyed much of the local habitat.","城市扩张破坏了当地大量栖息地。","environment","环境/动物/生态","habit(=live 居住)+at","home; environment; dwelling place","natural habitat; habitat loss; habitat destruction","写作：habitat loss/destruction 搭配 biodiversity 使用",2],

/* ---------------- 科技 technology ---------------- */
["innovation","/ˌɪnəˈveɪʃn/","n.","创新；新方法","a new idea, method or product","Technological innovation drives long-term economic growth.","技术创新推动长期经济增长。","technology","科技/经济/发展","in-(进入)+nov(=new 新)+ation","invention; breakthrough; novelty","technological innovation; drive innovation; foster innovation","写作：driver of innovation；口语 Part1 聊 technology",2],
["automation","/ˌɔːtəˈmeɪʃn/","n.","自动化","the use of machines to do work without humans","Automation may replace many routine office jobs.","自动化可能取代许多常规办公室工作。","technology","科技/就业/未来","auto(=self 自己)+mat(=think/move)+ion","mechanisation; robotics; computerisation","industrial automation; automation of tasks; job automation","写作就业话题：automation and job displacement",2],
["breakthrough","/ˈbreɪkθruː/","n.","突破","an important discovery or development","The new battery is a breakthrough for electric vehicles.","这种新电池对电动汽车而言是一项突破。","technology","科技/进步/研究","break+through（打破穿过）","advance; discovery; leap","medical breakthrough; major breakthrough; scientific breakthrough","写作/口语：a major breakthrough in…",2],
["algorithm","/ˈælɡərɪðəm/","n.","算法","a set of rules used by a computer to solve problems","Social media algorithms decide what users see first.","社交媒体的算法决定用户先看到什么。","technology","科技/媒体/数据","源自波斯数学家 al-Khwarizmi","formula; procedure; computation method","search algorithm; recommendation algorithm; algorithm bias","写作媒体/科技话题：algorithmic bias",3],
["robotics","/rəʊˈbɒtɪks/","n.","机器人技术","the design and use of robots","Robotics is transforming modern manufacturing.","机器人技术正在改变现代制造业。","technology","科技/制造/未来","robot+ics(…学)","robot technology; automation engineering","robotics industry; advances in robotics; robotics research","写作：robotics and artificial intelligence 常并列",2],
["database","/ˈdeɪtəbeɪs/","n.","数据库","an organised collection of digital information","Hospitals keep patient records in a central database.","医院把病历保存在中央数据库中。","technology","科技/数据/管理","data(数据)+base(库)","data bank; repository; data store","large database; database management; store in a database","写作：data collection/storage；口语可提 online database",1],
["sophisticated","/səˈfɪstɪkeɪtid/","adj.","精密的；先进的；老练的","highly developed and complex","Spacecraft require extremely sophisticated software.","航天器需要极其精密的软件。","technology","科技/形容词/高阶","soph(=wise 智慧)+isticated","advanced; complex; refined","highly sophisticated; sophisticated technology; sophisticated system","写作高分形容词：sophisticated technology/equipment",3],
["obsolete","/ˈɒbsəliːt/","adj.","过时的；淘汰的","no longer used or needed","Many skills become obsolete within a decade.","许多技能在十年内就会过时。","technology","科技/变化/就业","ob-(相反)+solete(=use 用)","outdated; out of date; antiquated","become obsolete; obsolete technology; render obsolete","写作：become obsolete / skills outdated",3],
["digital","/ˈdɪdʒɪtl/","adj.","数字的；数码的","using computer technology, especially the internet","The digital divide still separates rural and urban students.","数字鸿沟仍在区分农村与城市学生。","technology","科技/社会/媒体","digit(手指/数字)+al","electronic; online; virtual","digital divide; digital devices; digital literacy","写作：the digital divide（数字鸿沟）高频话题词",2],
["device","/dɪˈvaɪs/","n.","设备；装置","a tool or machine made for a specific purpose","Mobile devices have changed how students study.","移动设备改变了学生的学习方式。","technology","科技/日常/工具","de-+vis(=see/divide)+e","gadget; apparatus; appliance","mobile device; electronic device; device usage","口语 Part1 高频：electronic devices / screen time",1],

/* ---------------- 健康 health ---------------- */
["obesity","/əʊˈbiːsəti/","n.","肥胖（症）","the condition of being extremely overweight","Childhood obesity has doubled in the last twenty years.","过去二十年儿童肥胖率翻了一倍。","health","健康/社会/饮食","obes(=fat 肥)+ity","overweight; corpulence","childhood obesity; obesity rate; rising obesity","写作健康类：rising obesity rates / childhood obesity",2],
["chronic","/ˈkrɒnɪk/","adj.","慢性的；长期的","lasting for a long time; recurring","Chronic diseases place a heavy burden on hospitals.","慢性病给医院带来沉重负担。","health","健康/疾病/医疗","chron(=time 时间)+ic","persistent; long-term; recurring","chronic illness; chronic disease; chronic pain","写作：chronic disease vs acute illness",2],
["immune","/ɪˈmjuːn/","adj.","免疫的；不受影响的","protected against a disease or influence","A balanced diet keeps the immune system strong.","均衡饮食能让免疫系统保持强健。","health","健康/医学/科学","im-(不)+mune(=service/公共义务)","resistant; protected; exempt","immune system; immune response; immune to","写作：strengthen the immune system",2],
["nutritious","/njuˈtrɪʃəs/","adj.","有营养的","containing substances needed for health","Schools should provide more nutritious meals.","学校应提供更营养的餐食。","health","健康/食物/饮食","nutri(=nourish 滋养)+ous","nourishing; wholesome; healthy","nutritious food; nutritious diet; highly nutritious","写作：nutritious diet / balanced diet 替换 healthy food",2],
["sedentary","/ˈsedntri/","adj.","久坐的；缺乏运动的","involving little physical activity","A sedentary lifestyle increases the risk of heart disease.","久坐的生活方式会增加心脏病风险。","health","健康/生活/工作","sed(=sit 坐)+entary","inactive; desk-bound; inactive lifestyle","sedentary lifestyle; sedentary work; sedentary habits","写作高分：a sedentary lifestyle 搭配 desk jobs",3],
["wellbeing","/ˌwelˈbiːɪŋ/","n.","幸福感；福祉","the state of being healthy and happy","Green spaces in cities improve residents' wellbeing.","城市绿地能提升居民的幸福感。","health","健康/心理/社会","well+being(存在状态)","welfare; happiness; quality of life","mental wellbeing; physical wellbeing; improve wellbeing","写作：mental/physical wellbeing 是万能论点词",2],
["vaccination","/ˌvæksɪˈneɪʃn/","n.","接种疫苗","the act of giving a vaccine to protect against disease","Widespread vaccination has nearly eliminated the disease.","广泛的疫苗接种几乎消灭了这种疾病。","health","健康/医疗/政策","vacc(=cow 牛，源自牛痘)+ination","immunisation; inoculation; jab","vaccination programme; mass vaccination; vaccination rate","写作：vaccination programme / immunisation campaign",2],
["therapy","/ˈθerəpi/","n.","治疗；疗法","treatment intended to relieve or heal a disorder","Talking therapy can be as effective as medication.","谈话疗法可以和药物一样有效。","health","健康/心理/医疗","therap(=heal 治疗)+y","treatment; remedy; rehabilitation","physical therapy; therapy session; undergo therapy","写作心理健康话题：therapy / counselling",2],
["epidemic","/ˌepɪˈdemɪk/","n./adj.","流行病；泛滥的","a widespread occurrence of a disease or problem","The government acted quickly to contain the epidemic.","政府迅速行动以控制疫情。","health","健康/社会/媒体","epi-(在…中)+dem(=people 人群)+ic","outbreak; plague; widespread problem","epidemic outbreak; contain an epidemic; obesity epidemic","写作比喻用法：an epidemic of obesity",2],
["hygiene","/ˈhaɪdʒiːn/","n.","卫生","conditions and practices that keep people healthy","Basic hygiene prevents the spread of infection.","基础卫生能防止感染传播。","health","健康/日常/公共","源自希腊健康女神 Hygieia","cleanliness; sanitation","personal hygiene; food hygiene; hygiene standards","写作：public hygiene / sanitation standards",2],

/* ---------------- 工作 work ---------------- */
["recruitment","/rɪˈkruːtmənt/","n.","招聘","the process of finding and hiring new staff","Online recruitment platforms have simplified hiring.","在线招聘平台简化了招聘流程。","work","工作/就业/管理","re-(再)+cruit(=grow 增长)+ment","hiring; staffing; selection","recruitment process; staff recruitment; recruitment agency","写作：recruitment process / hiring practices",2],
["productivity","/ˌprɒdʌkˈtɪvəti/","n.","生产力；效率","the rate at which goods or work are produced","Flexible hours can improve employee productivity.","弹性工时能提升员工效率。","work","工作/经济/管理","product+ivity","output; efficiency; performance","boost productivity; labour productivity; productivity gains","写作：boost/improve productivity 高频动宾搭配",2],
["redundancy","/rɪˈdʌndənsi/","n.","裁员；冗余","the state of losing a job because it is no longer needed","The factory closure led to hundreds of redundancies.","工厂关闭导致数百人失业。","work","工作/就业/经济","red-(再)+und(=wave 波)+ancy","lay-off; dismissal; job loss","make redundant; redundancy payment; forced redundancy","写作：make workers redundant（注意与 unnecessary 区分）",3],
["deadline","/ˈdedlaɪn/","n.","截止期限","the latest time by which something must be done","Tight deadlines can cause stress in the workplace.","紧迫的截止期限会在职场造成压力。","work","工作/压力/管理","dead(死)+line(线)，逾期即失效","cut-off; time limit; target date","meet a deadline; tight deadline; miss a deadline","写作/口语：meet the deadline / under pressure",1],
["promotion","/prəˈməʊʃn/","n.","晋升；推广","advancement to a higher position; advertising","She received a promotion after two years of hard work.","努力两年后她获得了晋升。","work","工作/职业/商业","pro-(向前)+mot(=move 移动)+ion","advancement; elevation; upgrade","get a promotion; promotion opportunity; sales promotion","写作：career advancement/promotion prospects",1],
["collaboration","/kəˌlæbəˈreɪʃn/","n.","合作；协作","working together with others","The project succeeded because of close collaboration.","项目因密切协作而成功。","work","工作/团队/研究","col-(共同)+labor(=work 工作)+ation","teamwork; cooperation; partnership","close collaboration; international collaboration; in collaboration with","写作：in collaboration with / teamwork skills",2],
["freelance","/ˈfriːlɑːns/","adj./v./n.","自由职业的；自由职业者","working for different companies rather than one employer","More young people choose freelance work for flexibility.","更多年轻人为了灵活性选择自由职业。","work","工作/就业/趋势","free+lance(长枪→自由骑士)","self-employed; independent; contract-based","freelance work; freelance journalist; work freelance","写作就业趋势：the gig economy, freelance work",2],
["commute","/kəˈmjuːt/","v./n.","通勤","to travel regularly to and from work","A long daily commute can reduce life satisfaction.","每天长时间通勤会降低生活满意度。","work","工作/交通/生活","com-(共同)+mute(=change 交换)","travel; journey; daily travel","daily commute; commuting time; long commute","写作：long commuting times / rush hour",2],
["workload","/ˈwɜːkləʊd/","n.","工作量","the amount of work a person has to do","Teachers often complain about an excessive workload.","教师常抱怨工作量过大。","work","工作/压力/管理","work+load(负荷)","work burden; caseload; volume of work","heavy workload; reduce workload; manageable workload","写作：heavy workload / excessive workload",2],
["incentive","/ɪnˈsentɪv/","n.","激励；动机","something that encourages people to act","Tax incentives encourage companies to go green.","税收激励鼓励企业走绿色路线。","work","工作/政策/经济","in-+cant(=sing 唱)+ive，原指唱歌鼓劲","motivation; stimulus; encouragement","financial incentive; tax incentive; incentive to work","写作：financial incentives / provide an incentive",2]
,

/* ---------------- 旅游 travel ---------------- */
["itinerary","/aɪˈtɪnərəri/","n.","行程；行程单","a planned route or journey schedule","Our itinerary includes three cities in seven days.","我们的行程包含七天内游览三座城市。","travel","旅游/计划/行程","it(=go 走)+inerary","schedule; route; travel plan","detailed itinerary; travel itinerary; plan an itinerary","口语 Part2 描述旅行：a packed itinerary",3],
["accommodation","/əˌkɒməˈdeɪʃn/","n.","住宿","a place to stay, such as a hotel or flat","Affordable accommodation is hard to find in peak season.","旺季很难找到价格合适的住宿。","travel","旅游/住宿/费用","ac-(到)+commod(=fit 合适)+ation","housing; lodging; place to stay","find accommodation; accommodation costs; tourist accommodation","写作旅游话题：accommodation prices / local housing",2],
["destination","/ˌdestɪˈneɪʃn/","n.","目的地","the place someone is going to","The island has become a popular holiday destination.","这座岛已成为热门的度假目的地。","travel","旅游/地点/趋势","de-+stin(=stand 站)+ation","resort; target place; holiday spot","popular destination; tourist destination; final destination","写作/口语：a popular tourist destination",1],
["excursion","/ɪkˈskɜːʃn/","n.","短途旅行；远足","a short trip taken for pleasure","The school organised an excursion to the museum.","学校组织了一次去博物馆的短途旅行。","travel","旅游/学校/活动","ex-(出)+curs(=run 跑)+ion","outing; trip; day trip","school excursion; day excursion; go on an excursion","口语 Part2：a day excursion 比 trip 更具体",3],
["hospitality","/ˌhɒspɪˈtæləti/","n."," hospitality 好客；接待业","friendly treatment of guests; the hotel and catering industry","The hospitality industry employs millions of people.","接待服务业雇佣了数百万人。","travel","旅游/服务/就业","hospit(=guest 客人)+ality","welcome; friendliness; service industry","hospitality industry; warm hospitality; hospitality sector","写作：the hospitality sector / tourism industry",2],
["landmark","/ˈlændmɑːk/","n.","地标；里程碑","a notable building or an important event","The tower is the most famous landmark in the city.","这座塔是该市最著名的地标。","travel","旅游/城市/建筑","land(土地)+mark(标记)","monument; icon; milestone","famous landmark; historic landmark; landmark building","口语 Part2 描述城市/建筑必备词",1],
["souvenir","/ˌsuːvəˈnɪə/","n.","纪念品","an object kept as a reminder of a place","Tourists often buy souvenirs from local markets.","游客常在当地市场购买纪念品。","travel","旅游/购物/文化","sou-(sub 次)+venir(=come 来)","keepsake; memento; reminder","buy souvenirs; souvenir shop; local souvenir","写作：souvenir shops / tourist traps",2],
["cruise","/kruːz/","n./v.","乘船游览；巡航","a holiday on a ship; to sail for pleasure","A cruise around the islands costs less than you think.","环岛游轮的费用比你想象的低。","travel","旅游/交通/休闲","cruis(=cross 交叉/巡航)","voyage; sail; boat trip","cruise ship; go on a cruise; cruise holiday","口语 Part1/2 旅游话题可用",2],
["customs","/ˈkʌstəmz/","n.","海关","the government office controlling goods entering a country","We were delayed at customs for over an hour.","我们在海关被耽搁了一个多小时。","travel","旅游/法律/出入境","custom(惯例)+s","border control; immigration checkpoint","customs officer; go through customs; customs duty","写作全球化话题：customs duties / border controls",2],
["expedition","/ˌekspəˈdɪʃn/","n.","探险；考察","a journey made for a specific purpose","The team led an expedition to the remote valley.","团队带队去偏远山谷考察。","travel","旅游/科学/探险","ex-(出)+ped(=foot 脚)+ition","journey; exploration; mission","scientific expedition; mountaineering expedition; lead an expedition","写作/口语高阶替换：a scientific expedition",3],

/* ---------------- 文化 culture ---------------- */
["heritage","/ˈherɪtɪdʒ/","n.","遗产；传统","the history and traditions passed down through generations","The old town is protected as a world heritage site.","这座古城作为世界遗产地受到保护。","culture","文化/历史/保护","herit(=heir 继承)+age","legacy; inheritance; tradition","cultural heritage; heritage site; national heritage","写作：cultural heritage / heritage preservation",2],
["ritual","/ˈrɪtʃuəl/","n./adj.","仪式；惯例","a fixed set of actions, often religious or traditional","The festival follows an ancient ritual.","这个节庆遵循一种古老的仪式。","culture","文化/宗教/传统","rit(=rite 仪式)+ual","ceremony; tradition; custom","religious ritual; daily ritual; ritual practice","写作文化类：traditional rituals and customs",3],
["ethnicity","/eθˈnɪsəti/","n.","族裔；种族归属","the fact of belonging to a particular ethnic group","The city is proud of its mix of ethnicities.","这座城市为其多元族裔构成而自豪。","culture","文化/社会/多元","ethn(=nation 民族)+icity","race; ethnic origin; cultural background","ethnic diversity; different ethnicities; ethnicity data","写作多元文化：ethnic diversity / multicultural society",3],
["folklore","/ˈfəʊklɔː/","n.","民间传说；民俗","traditional stories and beliefs of a community","Local folklore attracts many curious visitors.","当地民俗吸引了许多好奇的游客。","culture","文化/传统/故事","folk(民间)+lore(学问)","myth; legend; oral tradition","local folklore; folklore story; folklore tradition","写作文化话题：local folklore and traditions",3],
["identity","/aɪˈdentəti/","n.","身份；认同","who a person or group is; a sense of belonging","Language is central to cultural identity.","语言是文化认同的核心。","culture","文化/社会/心理","ident(=same 相同)+ity","character; sense of self; belonging","cultural identity; national identity; sense of identity","写作：cultural identity / sense of belonging",2],
["assimilation","/əˌsɪməˈleɪʃn/","n.","同化；吸收","the process of adapting to a new culture","Assimilation can weaken minority languages.","同化可能削弱少数族群的语言。","culture","文化/社会/移民","as-(到)+simil(=similar 相同)+ation","integration; absorption; acculturation","cultural assimilation; assimilation policy; resist assimilation","写作移民话题：assimilation vs cultural diversity",3],
["ceremony","/ˈserəməni/","n.","典礼；仪式","a formal event held on a special occasion","The opening ceremony was watched by millions.","开幕式有数百万人观看。","culture","文化/活动/正式","cere(=care/reverence)+mony"," rite; celebration; formal event","opening ceremony; wedding ceremony; award ceremony","口语 Part2 描述事件常用",1],
["dialect","/ˈdaɪəlekt/","n.","方言","a regional form of a language","The village still speaks an old dialect.","这个村子仍讲一种古老方言。","culture","文化/语言/地区","dia-(之间)+lect(=speak 说)","regional language; vernacular; local speech","local dialect; speak a dialect; dialect variation","写作语言话题：dialects and minority languages",2],
["taboo","/təˈbuː/","n./adj.","禁忌；忌讳的","something forbidden by social custom","Mental health used to be a taboo subject.","心理健康曾经是个禁忌话题。","culture","文化/社会/话题","源自波利尼西亚语 tapu（神圣禁止）","prohibition; forbidden topic; no-go area","taboo subject; cultural taboo; break a taboo","写作：break the taboo / a taboo subject",3],
["indigenous","/ɪnˈdɪdʒənəs/","adj.","本土的；原住民的","originating naturally in a particular place","Indigenous communities protect large areas of forest.","原住民社区保护着大片森林。","culture","文化/环境/社会","indi-(内部)+gen(=birth 出生)+ous","native; original; aboriginal","indigenous people; indigenous language; indigenous culture","写作：indigenous communities/peoples（注意大写尊重用法）",3],

/* ---------------- 社会 society ---------------- */
["inequality","/ˌɪnɪˈkwɒləti/","n.","不平等","the unfair difference between groups of people","Income inequality has widened in many countries.","许多国家的收入差距扩大了。","society","社会/经济/问题","in-(不)+equal(平等)+ity","disparity; gap; imbalance","income inequality; social inequality; widen inequality","写作：income inequality / the gap between rich and poor",2],
["demographic","/ˌdeməˈɡræfɪk/","adj./n.","人口的；人群结构","relating to the structure of a population","An ageing demographic puts pressure on pensions.","老龄化的人口结构给养老金带来压力。","society","社会/人口/数据","demo(=people 人民)+graph(=write 记录)+ic","population; population group; statistic","ageing demographic; demographic change; demographic data","写作：an ageing population / demographic shift",3],
["welfare","/ˈwelfeə/","n.","福利；福祉","help given to people in need; general wellbeing","The state provides welfare for unemployed citizens.","国家为失业公民提供福利。","society","社会/政策/政府","well(好)+fare(=go 走)，原指过得好","benefits; social security; wellbeing","social welfare; welfare system; welfare benefits","写作政府类：welfare system / social safety net",2],
["poverty","/ˈpɒvəti/","n.","贫困","the state of being extremely poor","Education is the most effective way to escape poverty.","教育是摆脱贫困最有效的途径。","society","社会/经济/问题","pover(=poor 穷)+ty","destitution; hardship; deprivation","live in poverty; poverty line; reduce poverty","写作：poverty alleviation / lift people out of poverty",1],
["migration","/maɪˈɡreɪʃn/","n.","迁移；移民","movement of people from one place to another","Rural-to-urban migration is reshaping the country.","从农村到城市的迁移正在重塑这个国家。","society","社会/人口/城市","migr(=move 移动)+ation","movement; relocation; emigration","mass migration; internal migration; migration patterns","写作：rural-to-urban migration / migration flows",2],
["discrimination","/dɪˌskrɪmɪˈneɪʃn/","n.","歧视","unfair treatment based on group membership","Laws should prohibit discrimination in the workplace.","法律应禁止职场歧视。","society","社会/法律/公平","dis-(分开)+crimin(=judge 判断)+ation","bias; prejudice; unfair treatment","racial discrimination; gender discrimination; fight discrimination","写作：gender/racial discrimination；动词 discriminate against",2],
["charity","/ˈtʃærəti/","n.","慈善（机构）；仁爱","an organisation that helps people in need","She donates part of her salary to charity every month.","她每月把一部分工资捐给慈善机构。","society","社会/公益/志愿","char(=care/dear 关爱)+ity","non-profit; donation; benevolence","donate to charity; charity organisation; local charity","写作：charitable organisations / voluntary work",1],
["volunteer","/ˌvɒlənˈtɪə/","n./v.","志愿者；自愿做","a person who works without being paid","Hundreds of volunteers helped clean the beach.","数百名志愿者帮忙清理了海滩。","society","社会/公益/社区","volunt(=will 意愿)+eer(人)","unpaid worker; helper; offer help","volunteer work; trainee volunteer; volunteer to help","口语 Part1/2 高频：volunteer work / community service",2],
["solidarity","/ˌsɒlɪˈdærəti/","n.","团结；声援","unity based on shared interests or sympathy","The disaster created a sense of national solidarity.","灾难唤起了全国团结一致的感受。","society","社会/情感/群体","solid(坚固的)+arity","unity; cohesion; mutual support","show solidarity; sense of solidarity; social solidarity","写作：social cohesion / a sense of solidarity",3],
["norm","/nɔːm/","n.","规范；常态","a standard or typical pattern of behaviour","Social norms about work have changed dramatically.","关于工作的社会规范已发生巨变。","society","社会/行为/文化","norm(=rule/标准)","standard; convention; expectation","social norm; cultural norm; break the norm","写作：social norms / conform to norms",2],

/* ---------------- 法律 law ---------------- */
["legislation","/ˌledʒɪsˈleɪʃn/","n.","立法；法规","a law or set of laws made by a government","New legislation bans single-use plastics.","新法规禁止一次性塑料。","law","法律/政府/政策","legis(=law 法律)+lation","law; statute; regulation","introduce legislation; pass legislation; environmental legislation","写作政府类：introduce/enact legislation",2],
["penalty","/ˈpenəlti/","n.","处罚；惩罚","a punishment for breaking a rule or law","The penalty for dumping waste is a heavy fine.","倾倒垃圾的处罚是高额罚款。","law","法律/惩罚/规则","pen(=punish 惩罚)+alty","punishment; fine; sanction","heavy penalty; impose a penalty; death penalty","写作：impose penalties / tougher penalties",2],
["enforcement","/ɪnˈfɔːsmənt/","n.","执行；执法","the act of making people obey a law","Strict enforcement is more important than new laws.","严格执法比制定新法更重要。","law","法律/政府/执行","en-(使)+force(力量)+ment","implementation; policing; compliance check","law enforcement; enforce the law; strict enforcement","写作：law enforcement / enforce regulations",2],
["compliance","/kəmˈplaɪəns/","n.","遵守；合规","the act of obeying a rule or request","Companies must prove compliance with safety rules.","企业必须证明其遵守安全规定。","law","法律/商业/管理","com-+pli(=fill 填满)+ance","obedience; conformity; adherence","compliance with; regulatory compliance; ensure compliance","写作：compliance with regulations（搭配 in compliance with）",3],
["amendment","/əˈmendmənt/","n.","修正案；修改","a change made to a law or document","The amendment to the act was passed last year.","该法案的修正案去年获得通过。","law","法律/政治/变更","a-+mend(=repair 修补)+ment","revision; modification; adjustment","constitutional amendment; propose an amendment; draft amendment","写作：amend the law / propose an amendment",3],
["prosecute","/ˈprɒsɪkjuːt/","v.","起诉；追究刑事责任","to bring a legal case against someone","Companies that pollute rivers should be prosecuted.","污染河流的企业应被起诉。","law","法律/犯罪/动词","pro-(向前)+secut(=follow 追随)","charge; sue; take to court","prosecute offenders; prosecute a case; face prosecution","写作：prosecute offenders / face prosecution",3],
["regulation","/ˌreɡjuˈleɪʃn/","n.","规章；监管","an official rule; the control of an activity","Stricter regulation of advertising is needed.","需要对广告进行更严格的监管。","law","法律/政府/商业","reg(=rule 统治/直)+ulation","rule; directive; control","strict regulation; government regulation; safety regulation","写作：government regulation / deregulation 对比",2],
["liability","/ˌlaɪəˈbɪləti/","n.","责任；负债","legal responsibility; money owed","Manufacturers carry liability for faulty products.","制造商对缺陷产品承担责任。","law","法律/商业/责任","li(=bind 绑)+ability→被绑住的责任","responsibility; obligation; accountability","legal liability; limited liability; liability for","写作：legal liability / hold sb liable",3],
["lawsuit","/ˈlɔːsuːt/","n.","诉讼","a claim or dispute taken to a court","The firm faced a lawsuit over unsafe working conditions.","该公司因不安全的工作条件面临诉讼。","law","法律/商业/纠纷","law(法律)+suit(诉讼)","case; legal action; litigation","file a lawsuit; face a lawsuit; lawsuit against","写作：file a lawsuit / take legal action",2],
["constitution","/ˌkɒnstɪˈtjuːʃn/","n.","宪法；体质","the basic laws and principles of a state","The constitution guarantees freedom of speech.","宪法保障言论自由。","law","法律/政府/政治","con-(共同)+stitut(=stand 建立)+ion","charter; founding law; basic law","the constitution; constitutional right; amend the constitution","写作：constitutional rights / the rule of law",2],

/* ---------------- 媒体 media ---------------- */
["coverage","/ˈkʌvərɪdʒ/","n.","报道；覆盖范围","the reporting of news; the extent covered","Media coverage of the issue has been extensive.","媒体对该问题的报道非常广泛。","media","媒体/新闻/社会","cover(覆盖)+age","reporting; news report; publicity","media coverage; extensive coverage; news coverage","写作：media coverage of… / extensive coverage",2],
["censorship","/ˈsensəʃɪp/","n.","审查（制度）","the control of what people can see or say","Internet censorship limits access to information.","网络审查限制了信息获取。","media","媒体/政府/自由","cens(=judge 评判)+orship","suppression; control; restriction","internet censorship; impose censorship; censorship laws","写作：freedom of speech vs censorship",3],
["bias","/ˈbaɪəs/","n.","偏见；偏向","an unfair preference for one side","Readers should be aware of media bias.","读者应意识到媒体偏见。","media","媒体/社会/态度","源自法语 biais（斜）","prejudice; partiality; slant","media bias; cognitive bias; bias against","写作：media bias / biased reporting",2],
["journalist","/ˈdʒɜːnəlɪst/","n.","记者","a person who writes news articles","Investigative journalists expose corruption.","调查记者揭露腐败。","media","媒体/职业/新闻","journal(=day 每日记录)+ist","reporter; correspondent; news writer","investigative journalist; professional journalist; work as a journalist","口语 Part2 描述敬佩的人可用",1],
["broadcast","/ˈbrɔːdkɑːst/","n./v.","广播；播出","a radio or television programme; to transmit","The debate was broadcast live last night.","这场辩论昨晚进行了直播。","media","媒体/技术/新闻","broad(广)+cast(投)","transmission; airing; telecast","live broadcast; broadcast live; television broadcast","写作：live broadcast / broadcasting industry",2],
["propaganda","/ˌprɒpəˈɡændə/","n.","宣传（常含贬义）","information used to influence opinions, often misleading","Wartime propaganda shaped public opinion.","战时宣传塑造了公众舆论。","media","媒体/政治/负面","propag(=propagate 传播)+anda","indoctrination; spin; disinformation","political propaganda; spread propaganda; propaganda campaign","写作：propaganda vs objective reporting",3],
["viral","/ˈvaɪrəl/","adj.","病毒式传播的","spreading rapidly online","The video went viral within hours.","这段视频几小时内就火遍网络。","media","媒体/网络/流行","vir(=poison/virus 病毒)+al","widely shared; trending; spread rapidly","go viral; viral video; viral content","口语 Part1 internet 话题高频：go viral",2],
["tabloid","/ˈtæblɔɪd/","n./adj.","小报；八卦的","a small newspaper with sensational stories","Tabloids often focus on celebrities rather than facts.","小报通常关注名人而非事实。","media","媒体/新闻/娱乐","tablet(压缩药片)+oid，原指压缩版报纸","popular press; gossip paper; yellow press","tabloid newspaper; tabloid press; tabloid headlines","写作：tabloid press vs quality press",3],
["credibility","/ˌkredəˈbɪləti/","n.","可信度","the quality of being trusted and believed","Fake news damages the credibility of journalism.","假新闻损害了新闻业的可信度。","media","媒体/信任/品质","cred(=believe 相信)+ibility","reliability; trustworthiness; authority","undermine credibility; gain credibility; credibility of","写作：undermine credibility / reliable sources",3],
["exposure","/ɪkˈspəʊʒə/","n.","曝光；接触","the state of being exposed to something","Constant exposure to screens affects sleep quality.","持续接触屏幕会影响睡眠质量。","media","媒体/健康/社会","ex-(出)+pos(=put 放)+ure","contact; publicity; revelation","exposure to; media exposure; prolonged exposure","写作：exposure to violent content / screen exposure",2]
,

/* ---------------- 经济 economy ---------------- */
["inflation","/ɪnˈfleɪʃn/","n.","通货膨胀","a general rise in prices over time","Inflation erodes the purchasing power of wages.","通货膨胀侵蚀了工资的购买力。","economy","经济/价格/政策","in-(进入)+flat(=blow 吹)+ion","price rise; rising costs","high inflation; inflation rate; control inflation","写作：inflation rate / rising cost of living",2],
["recession","/rɪˈseʃn/","n.","经济衰退","a period of economic decline","The recession forced many small firms to close.","经济衰退迫使许多小企业关闭。","economy","经济/就业/危机","re-(回)+cess(=go 走)+ion","downturn; slump; economic decline","economic recession; enter a recession; deep recession","写作：economic downturn/recession",2],
["expenditure","/ɪkˈspendɪtʃə/","n.","支出；开销","the money spent on something","Public expenditure on health has increased.","公共卫生支出已增加。","economy","经济/政府/数据","ex-(出)+pend(=weigh/pay 支付)+iture","spending; outlay; cost","public expenditure; household expenditure; capital expenditure","图表题高频：public expenditure / household spending",3],
["subsidy","/ˈsʌbsədi/","n.","补贴；津贴","money given by the government to support something","Subsidies for rail travel reduce car use.","对铁路出行的补贴能减少汽车使用。","economy","经济/政策/环境","sub-(下)+sid(=sit 坐)+y，原指在下支撑","grant; allowance; financial aid","government subsidy; provide subsidies; agricultural subsidy","写作：provide/offer subsidies",3],
["revenue","/ˈrevənjuː/","n.","收入；税收","income earned by a business or government","Tourism generates significant revenue for the region.","旅游业为该地区创造了可观收入。","economy","经济/商业/政府","re-(回)+venue(=come 来)","income; earnings; turnover","generate revenue; tax revenue; government revenue","写作：generate revenue / tax revenue",2],
["deficit","/ˈdefɪsɪt/","n.","赤字；不足","the amount by which spending exceeds income","The country runs a large trade deficit.","该国存在巨额贸易赤字。","economy","经济/贸易/政府","de-(向下)+fic(=do/make 做)+it","shortfall; gap; shortfall in funds","budget deficit; trade deficit; cover a deficit","写作：budget deficit / trade deficit",3],
["fluctuation","/ˌflʌktʃuˈeɪʃn/","n.","波动","frequent changes up and down","Price fluctuations make planning difficult.","价格波动使规划变得困难。","economy","经济/数据/变化","fluct(=wave 波浪)+uation","variation; volatility; instability","price fluctuation; currency fluctuation; seasonal fluctuation","图表题必备：fluctuate / fluctuation",3],
["austerity","/ɒˈsterəti/","n.","紧缩（政策）","reduced public spending during economic difficulty","Austerity measures cut public services sharply.","紧缩措施大幅削减了公共服务。","economy","经济/政策/政府","austere(严峻)+ity","spending cuts; belt-tightening; retrenchment","austerity measures; austerity policy; impose austerity","写作政府经济话题高阶词",3],
["globalisation","/ˌɡləʊbəlaɪˈzeɪʃn/","n.","全球化","the process of countries becoming more connected","Globalisation has spread ideas as well as goods.","全球化传播了商品，也传播了思想。","economy","经济/社会/趋势","global(全球)+isation","internationalisation; worldwide integration","economic globalisation; globalisation of trade; impact of globalisation","写作：the impact of globalisation",2],
["tariff","/ˈtærɪf/","n.","关税","a tax on imported or exported goods","High tariffs can start a trade dispute.","高关税可能引发贸易争端。","economy","经济/贸易/政策","源自阿拉伯语 tariff（价目表）","duty; customs duty; import tax","import tariff; impose tariffs; tariff barrier","写作：impose tariffs / trade barriers",3],

/* ---------------- 政府 government ---------------- */
["bureaucracy","/bjʊəˈrɒkrəsi/","n.","官僚体制；繁文缛节","a system of government by officials; excessive procedure","Excessive bureaucracy slows down public projects.","过度的官僚程序拖慢了公共项目。","government","政府/管理/负面","bureau(办公桌/局)+cracy(=rule 统治)","administration; officialdom; red tape","government bureaucracy; reduce bureaucracy; bureaucratic process","写作：bureaucratic red tape",3],
["governance","/ˈɡʌvənəns/","n.","治理；管理","the way an organisation or country is managed","Good governance requires transparency and accountability.","良好的治理需要透明与问责。","government","政府/管理/政策","govern(统治)+ance","administration; management; leadership","good governance; corporate governance; local governance","写作：good governance / transparent governance",3],
["mandate","/ˈmændeɪt/","n./v.","授权；命令","an official order or authority to act","The elected government has a clear mandate for reform.","当选政府拥有明确的改革授权。","government","政府/政治/权力","man(=hand 手)+dat(=give 给)","authority; instruction; directive","clear mandate; electoral mandate; mandate reform","写作：electoral mandate / mandate for change",3],
["referendum","/ˌrefəˈrendəm/","n.","公投","a public vote on a single political question","The government held a referendum on the new law.","政府就新法律举行了公投。","government","政府/政治/民主","refer(提交)+endum(应被…)","public vote; plebiscite; ballot","hold a referendum; national referendum; referendum on","写作：hold a referendum / direct democracy",3],
["taxation","/tækˈseɪʃn/","n.","税收；税制","the system of collecting taxes","Higher taxation on fuel discourages driving.","提高燃油税能抑制开车出行。","government","政府/经济/政策","tax+ation","tax system; levies; duties","taxation system; income taxation; level of taxation","写作：taxation policy / tax revenue",2],
["diplomacy","/dɪˈpləʊməsi/","n.","外交","the management of relations between countries","Diplomacy prevented the dispute from escalating.","外交手段阻止了争端升级。","government","政府/国际/关系","diploma(文书)+cy","negotiation; statecraft; foreign affairs","international diplomacy; diplomatic relations; through diplomacy","写作国际关系话题：diplomatic solutions",3],
["allocation","/ˌæləˈkeɪʃn/","n.","分配；划拨","the act of giving resources for a purpose","Better allocation of resources improves public services.","更合理的资源配置能改善公共服务。","government","政府/资源/管理","al-(到)+loc(=place 位置)+ation","distribution; assignment; apportionment","resource allocation; budget allocation; allocate funds","写作：allocate resources/funds",3],
["reform","/rɪˈfɔːm/","n./v.","改革","a change made to improve a system","Education reform is high on the political agenda.","教育改革在政治议程上排名靠前。","government","政府/社会/变革","re-(再)+form(形状)","change; improvement; restructuring","education reform; reform the system; economic reform","写作：reform the system / policy reform",2],
["transparency","/trænsˈpærənsi/","n.","透明度","the quality of being open and easy to check","Transparency reduces corruption in public spending.","透明度能减少公共支出中的腐败。","government","政府/管理/反腐","trans-(穿过)+par(=appear 显现)+ency","openness; accountability; clarity","greater transparency; ensure transparency; lack of transparency","写作：transparency and accountability",3],
["parliament","/ˈpɑːləmənt/","n.","议会","the group of people who make a country's laws","Parliament debated the new education bill.","议会就新的教育法案进行了辩论。","government","政府/法律/政治","parl(=speak 说)+iament","legislature; assembly; congress","parliament debate; member of parliament; pass through parliament","写作：the legislature / pass a bill",2],

/* ---------------- 犯罪 crime ---------------- */
["offence","/əˈfens/","n.","违法行为；冒犯","an act that breaks the law; an insult","Drink-driving is a serious criminal offence.","酒后驾车是严重的刑事违法行为。","crime","犯罪/法律/社会","of-(against)+fence(=strike 打击)","crime; violation; misdemeanour","criminal offence; commit an offence; minor offence","写作：commit an offence / criminal offence",2],
["deterrence","/dɪˈterəns/","n.","威慑","the action of discouraging an action by fear of consequences","Tough sentences provide little deterrence.","重刑几乎起不到威慑作用。","crime","犯罪/法律/政策","de-(离开)+terr(=frighten 恐吓)+ence","prevention; discouragement; deterrent","act as a deterrent; deterrence effect; nuclear deterrence","写作：a deterrent to crime / deter potential offenders",3],
["rehabilitation","/ˌriːhəˌbɪlɪˈteɪʃn/","n.","改造；康复","restoring someone to normal life after prison or illness","Rehabilitation programmes reduce reoffending rates.","改造项目能降低再犯率。","crime","犯罪/法律/社会","re-(再)+habil(=ability 能力)+itation","reintegration; recovery; retraining","rehabilitation programme; offender rehabilitation; rehabilitation centre","写作：rehabilitation vs punishment",3],
["theft","/θeft/","n.","盗窃","the act of stealing","Car theft has fallen since cameras were installed.","安装摄像头后汽车盗窃案减少了。","crime","犯罪/社会/安全","来自 thieve/steal 的名词形式","stealing; robbery; burglary","car theft; theft rate; petty theft","写作：petty theft / burglary rate",2],
["vandalism","/ˈvændəlɪzəm/","n.","故意破坏公物","deliberately damaging public property","Vandalism in parks costs the council millions.","公园里的破坏公物行为让市政损失数百万。","crime","犯罪/社会/城市","Vandal(汪达尔人)+ism","damage; destruction; defacement","acts of vandalism; vandalism rates; commit vandalism","写作：anti-social behaviour / vandalism",3],
["fraud","/frɔːd/","n.","欺诈","wrongful deception for financial gain","Online fraud has increased with digital payments.","随着数字支付普及，网络欺诈增多。","crime","犯罪/网络/经济","fraud(=deceit 欺骗)","scam; deception; swindle","online fraud; credit card fraud; commit fraud","写作：online fraud / financial scams",2],
["juvenile","/ˈdʒuːvənaɪl/","adj./n.","青少年的；少年","relating to young people; a young person","Juvenile crime is often linked to family background.","青少年犯罪常与家庭背景有关。","crime","犯罪/社会/青少年","juven(=young 年轻)+ile","youth; adolescent; teenage","juvenile crime; juvenile offender; juvenile justice","写作：juvenile delinquency / young offenders",3],
["incarceration","/ɪnˌkɑːsəˈreɪʃn/","n.","监禁","the state of being imprisoned","Incarceration rates are among the highest in the world.","监禁率位居世界前列。","crime","犯罪/法律/社会","in-(进入)+carcer(=prison 监狱)+ation","imprisonment; custody; confinement","rate of incarceration; mass incarceration; incarceration period","写作：imprisonment / custodial sentences",3],
["recidivism","/rɪˈsɪdɪvɪzəm/","n.","再犯；累犯","the tendency of offenders to reoffend","Education in prison lowers recidivism rates.","监狱中的教育能降低再犯率。","crime","犯罪/法律/数据","re-(回)+cid(=fall 落下)+ivism，再度跌倒","reoffending; repeat offending","recidivism rate; reduce recidivism; repeat offenders","写作用数据：reoffending rates",3],
["bribery","/ˈbraɪbəri/","n.","贿赂","the giving of money to influence someone","Bribery undermines trust in public institutions.","贿赂削弱了公众对机构的信任。","crime","犯罪/政府/腐败","bribe(贿赂)+ery","corruption; kickbacks; graft","bribery and corruption; accept bribes; bribery case","写作：corruption and bribery",3],

/* ---------------- 交通 transport ---------------- */
["infrastructure","/ˈɪnfrəstrʌktʃə/","n.","基础设施","the basic systems a country needs, such as roads and power","Investment in transport infrastructure boosts the economy.","交通基础设施投资能拉动经济。","transport","交通/城市/政府","infra-(下)+structure(结构)","public works; utilities; facilities","transport infrastructure; invest in infrastructure; infrastructure project","写作万能：invest in infrastructure",2],
["congestion","/kənˈdʒestʃən/","n.","拥堵","overcrowding, especially of traffic","Congestion charging has reduced traffic in the centre.","拥堵收费减少了市中心的车流。","transport","交通/城市/问题","con-(共同)+gest(=carry 带)+ion","jam; overcrowding; blockage","traffic congestion; congestion charge; ease congestion","写作：ease/reduce congestion；congestion charge",2],
["pedestrian","/pəˈdestriən/","n./adj.","行人；步行的","a person walking; relating to walking","The city built more pedestrian zones downtown.","该市在市中心修建了更多步行区。","transport","交通/城市/安全","ped(=foot 脚)+estrian","walker; passer-by; foot traveller","pedestrian zone; pedestrian bridge; pedestrian safety","写作：pedestrian-friendly streets / walkable cities",2],
["transit","/ˈtrænzɪt/","n.","公共交通；过境","the movement of people or goods; public transport","Public transit is cheaper than driving in big cities.","在大城市公共交通比开车便宜。","transport","交通/城市/系统","trans-(穿越)+it(=go 走)","transport; passage; commuting","public transit; transit system; mass transit","写作：mass transit / public transport",2],
["freight","/freɪt/","n.","货运；货物","goods transported in bulk","Rail freight produces less pollution than lorries.","铁路货运比卡车产生的污染更少。","transport","交通/物流/环境","与 fraught 同源，原指装载","cargo; shipment; goods","freight transport; rail freight; freight costs","写作：freight transport / logistics",3],
["bottleneck","/ˈbɒtlnek/","n.","瓶颈；拥堵点","a point where progress is slowed","The bridge is a bottleneck during rush hour.","高峰时段这座桥是个拥堵点。","transport","交通/问题/比喻","bottle(瓶)+neck(颈)","obstruction; choke point; blockage","traffic bottleneck; bottleneck in production; create a bottleneck","写作比喻用法：a bottleneck in…",3],
["fare","/feə/","n.","票价；车费","the money paid for a journey","Lower bus fares encourage people to leave cars at home.","降低公交票价能鼓励人们少开车。","transport","交通/费用/政策","fare(=go/travel)","ticket price; charge; fee","bus fare; fare increase; affordable fares","写作：subsidised fares / fare increases",2],
["accessibility","/əkˌsesəˈbɪləti/","n.","可达性；无障碍","the quality of being easy to reach or use","Accessibility for wheelchair users should be mandatory.","轮椅使用者的无障碍通行应当是强制的。","transport","交通/社会/设计","access(接近)+ibility","reachability; ease of access; inclusiveness","improve accessibility; accessibility for all; wheelchair accessibility","写作：accessibility / inclusive design",3],
["gridlock","/ˈɡrɪdlɒk/","n.","交通瘫痪；僵局","a complete standstill of traffic or progress","Gridlock costs the city hours of lost productivity.","交通瘫痪让城市损失数小时的生产力。","transport","交通/城市/问题","grid(网格)+lock(锁)","standstill; deadlock; traffic jam","traffic gridlock; political gridlock; cause gridlock","写作高阶：traffic gridlock",3],
["toll","/təʊl/","n.","通行费；代价","a charge for using a road or bridge; a cost in damage","The road toll has risen by twenty percent.","过路费上涨了百分之二十。","transport","交通/费用/政策","toll(计数/收费)","charge; fee; levy","road toll; toll road; pay a toll","写作：toll roads / congestion charge",3],

/* ---------------- 城市 city ---------------- */
["urbanisation","/ˌɜːbənaɪˈzeɪʃn/","n.","城市化","the growth of cities as people move in from rural areas","Rapid urbanisation strains housing and transport.","快速城市化给住房和交通带来压力。","city","城市/社会/趋势","urban(城市的)+isation","city growth; metropolitan expansion","rapid urbanisation; urbanisation rate; process of urbanisation","写作：rapid urbanisation 高频话题词",2],
["skyscraper","/ˈskaɪskreɪpə/","n.","摩天大楼","a very tall building","Glass skyscrapers dominate the financial district.","玻璃摩天大楼主导着金融区。","city","城市/建筑/经济","sky(天)+scrape(刮)+r","high-rise; tower block; tower","glass skyscraper; build skyscrapers; office skyscraper","口语 Part2 描述建筑可用",2],
["suburb","/ˈsʌbɜːb/","n.","郊区","an area on the edge of a city","Many families move to the suburb for more space.","许多家庭为更多空间搬到郊区。","city","城市/居住/生活","sub-(下/次)+urb(=city 城市)","outskirt; residential area; commuter town","live in the suburbs; suburban area; suburb of","写作：urban sprawl / suburban living",2],
["density","/ˈdensəti/","n.","密度","the number of people or things in a given area","High population density makes public transport viable.","高人口密度使公共交通变得可行。","city","城市/数据/规划","dens(=thick 浓密)+ity","concentration; compactness; crowdedness","population density; high density; housing density","图表题：population density",2],
["municipal","/mjuːˈnɪsɪpl/","adj.","市政的","relating to a city or its local government","Municipal budgets cover waste collection and parks.","市政预算涵盖垃圾清运和公园。","city","城市/政府/管理","muni(=public duty)+cip(=take 承担)+al","civic; local government; city-level","municipal government; municipal services; municipal authority","写作：local/municipal authorities",3],
["slum","/slʌm/","n.","贫民窟","a very poor and overcrowded urban area","Slum conditions worsen as migration accelerates.","随着移民加速，贫民窟状况恶化。","city","城市/贫困/社会","来源不明，原指陋巷","shanty town; deprived area; ghetto","slum area; live in a slum; slum clearance","写作：slum clearance / informal settlements",3],
["zoning","/ˈzəʊnɪŋ/","n.","分区规划","the division of land into areas for particular uses","Zoning laws separate industry from housing.","分区法规把工业与住宅分开。","city","城市/规划/法律","zone(区域)+ing","land-use planning; districting; land allocation","zoning laws; residential zoning; zoning regulations","写作：zoning regulations / urban planning",3],
["metropolitan","/ˌmetrəˈpɒlɪtən/","adj.","大都市的","relating to a large city and its surrounding area","Metropolitan areas produce most of the national output.","大都市区创造了全国大部分产出。","city","城市/经济/数据","metro(=mother 母城)+politan(=city)","urban; city-wide; cosmopolitan","metropolitan area; metropolitan region; metropolitan life","写作：metropolitan areas",3],
["gentrification","/ˌdʒentrɪfɪˈkeɪʃn/","n.","士绅化（旧区改造中产化）","the process of poorer areas becoming more middle-class","Gentrification raises rents and displaces residents.","士绅化推高租金并挤出原住民。","city","城市/社会/经济","gentry(绅士阶层)+fication","urban renewal; regeneration; upscaling","urban gentrification; gentrification process; resist gentrification","写作城市化高阶话题词",3],
["sanitation","/ˌsænɪˈteɪʃn/","n.","卫生设施；公共卫生","systems for keeping places clean, especially sewage","Poor sanitation spreads disease in crowded areas.","恶劣的卫生条件在拥挤地区传播疾病。","city","城市/健康/公共","san(=healthy 健康)+itation","hygiene; sewage system; public health","poor sanitation; sanitation system; improve sanitation","写作：sanitation and clean water",3]
,

/* ---------------- 乡村 rural ---------------- */
["agriculture","/ˈæɡrɪkʌltʃə/","n.","农业","the practice of growing crops and raising animals","Agriculture still employs a quarter of the population.","农业仍雇佣着四分之一的人口。","rural","乡村/经济/食物","agri(=field 田地)+cult(=till 耕作)+ure","farming; cultivation; agronomy","modern agriculture; agricultural land; agriculture sector","写作：agricultural production / farming",1],
["irrigation","/ˌɪrɪˈɡeɪʃn/","n.","灌溉","supplying land with water through channels","Efficient irrigation saves huge amounts of water.","高效灌溉能节约大量用水。","rural","乡村/农业/环境","ir-(进入)+rig(=water 水)+ation","watering; watering system; drainage","irrigation system; irrigation canal; drip irrigation","写作环境/农业：irrigation systems",3],
["livestock","/ˈlaɪvstɒk/","n.","牲畜","farm animals kept for use or profit","Drought has reduced livestock numbers in the region.","干旱使该地区的牲畜数量减少。","rural","乡村/农业/环境","live(活)+stock(存货)","farm animals; cattle; herds","raise livestock; livestock farming; livestock numbers","写作：livestock farming 与 vegetarianism 对比",2],
["harvest","/ˈhɑːvɪst/","n./v.","收成；收割","the gathering of ripe crops; to gather them","A poor harvest pushed food prices up.","歉收推高了食品价格。","rural","乡村/农业/食物","与 autumn 同源（收获季）","crop yield; gathering; reap","harvest season; poor harvest; harvest crops","写作：crop yields / harvest failure",2],
["fertile","/ˈfɜːtaɪl/","adj.","肥沃的；富饶的","able to produce abundantly","The valley has some of the most fertile soil in the country.","这个山谷拥有全国最肥沃的土壤。","rural","乡村/农业/自然","fer(=bear/carry 带来)+tile","productive; rich; arable","fertile soil; fertile land; highly fertile","写作：fertile land / arable land",2],
["pastoral","/ˈpɑːstərəl/","adj.","田园的；畜牧的","relating to countryside life or sheep farming","The painting shows an idealised pastoral scene.","这幅画描绘了理想化的田园场景。","rural","乡村/艺术/生活","pastor(=shepherd 牧羊人)+al","rural; rustic; bucolic","pastoral life; pastoral landscape; pastoral farming","写作文学/艺术话题可用",3],
["subsistence","/səbˈsɪstəns/","n.","勉强维持生计","the state of having only the minimum needed to live","Many families depend on subsistence farming.","许多家庭依靠自给农业维持生计。","rural","乡村/贫困/经济","sub-(下)+sist(=stand 站立)+ence","survival; livelihood; bare existence","subsistence farming; subsistence level; live at subsistence level","写作：subsistence farming / livelihood",3],
["orchard","/ˈɔːtʃəd/","n.","果园","an area of land where fruit trees are grown","The orchard produces apples for the local market.","这个果园为当地市场出产苹果。","rural","乡村/农业/食物","源自古英语 ortgeard（园地）","fruit garden; grove","apple orchard; fruit orchard; plant an orchard","口语 Part1 countryside 可用",2],
["isolation","/ˌaɪsəˈleɪʃn/","n.","隔绝；孤立","the state of being separated from others","Rural isolation limits access to healthcare.","乡村的闭塞限制了医疗服务的获取。","rural","乡村/社会/健康","isol(=island 岛)+ation","separation; seclusion; remoteness","social isolation; rural isolation; feel isolation","写作：social isolation / remote areas",2],
["depopulation","/ˌdiːˌpɒpjuˈleɪʃn/","n.","人口减少","a reduction in the number of people living in an area","Rural depopulation leaves villages with no school.","乡村人口减少导致一些村庄没有学校。","rural","乡村/社会/趋势","de-(去除)+population(人口)","population decline; out-migration; shrinking population","rural depopulation; cause depopulation; population decline","写作：rural depopulation / ageing villages",3],

/* ---------------- 艺术 art ---------------- */
["exhibition","/ˌeksɪˈbɪʃn/","n.","展览","a public display of art or objects","The museum hosts a photography exhibition each spring.","这家博物馆每年春天举办摄影展。","art","艺术/文化/活动","ex-(出)+hibit(=hold 持)+ion","show; display; showcase","art exhibition; hold an exhibition; exhibition hall","口语 Part2：an exhibition I visited",2],
["masterpiece","/ˈmɑːstəpiːs/","n.","杰作","an outstanding work of art or skill","The novel is regarded as her masterpiece.","这部小说被视为她的杰作。","art","艺术/文学/评价","master(大师)+piece(作品)","masterwork; magnum opus; classic","a masterpiece of; artistic masterpiece; create a masterpiece","写作/口语赞美用词",2],
["sculpture","/ˈskʌlptʃə/","n.","雕塑","a work of art made by shaping material","A bronze sculpture stands in the town square.","一尊青铜雕塑立在市镇广场上。","art","艺术/文化/城市","sculpt(=carve 雕刻)+ure","statue; carving; figure","bronze sculpture; modern sculpture; sculpture park","口语 Part2 描述艺术品",2],
["contemporary","/kənˈtemprəri/","adj.","当代的；同时代的","belonging to the present time","Contemporary art often challenges traditional ideas.","当代艺术常常挑战传统观念。","art","艺术/现代/文化","con-(共同)+tempor(=time 时间)+ary","modern; current; present-day","contemporary art; contemporary society; contemporary artist","写作：contemporary society（比 modern society 更学术）",2],
["aesthetic","/iːsˈθetɪk/","adj./n.","审美的；美感","concerned with beauty; a set of beauty principles","The building is functional rather than aesthetic.","这座建筑重实用而非美观。","art","艺术/设计/评价","aesthe(=perceive 感知)+tic","artistic; visual; beautiful","aesthetic value; aesthetic appeal; sense of aesthetics","写作：aesthetic value/appeal",3],
["gallery","/ˈɡæləri/","n.","画廊；美术馆","a room or building where art is shown","The gallery is free to enter on Sundays.","这家画廊周日免费开放。","art","艺术/文化/城市","gal(=gallant/长廊)+ery","art museum; exhibition space; salon","art gallery; visit a gallery; gallery owner","口语 Part2 描述去处",2],
["portrait","/ˈpɔːtreɪt/","n.","肖像；描绘","a painting or description of a person","She painted a portrait of her grandmother.","她为祖母画了一幅肖像。","art","艺术/人物/描述","por-(向前)+tray(=draw 拉/画)","likeness; depiction; representation","paint a portrait; family portrait; portrait of","口语 Part2 描述照片/画作",2],
["abstract","/ˈæbstrækt/","adj./n.","抽象的；摘要","existing as an idea, not a physical object","Abstract paintings can be hard to interpret.","抽象画可能难以解读。","art","艺术/概念/学术","abs-(离开)+tract(=pull 拉)","non-representational; conceptual; theoretical","abstract art; abstract concept; abstract idea","写作：abstract concepts（如 happiness, freedom）",2],
["patronage","/ˈpætrənɪdʒ/","n.","赞助；光顾","support given by a patron; customers' business","Royal patronage supported many artists in the past.","过去王室赞助扶持了许多艺术家。","art","艺术/经济/历史","patron(=father/保护人)+age","sponsorship; support; custom","royal patronage; artistic patronage; under the patronage of","写作历史/艺术话题高阶词",3],
["craftsmanship","/ˈkrɑːftsmənʃɪp/","n.","工艺；手艺","skill in making things by hand","The furniture is prized for its fine craftsmanship.","这些家具因其精湛工艺而受到珍视。","art","艺术/手工/评价","craft(手艺)+s+manship","workmanship; skill; artistry","fine craftsmanship; traditional craftsmanship; level of craftsmanship","写作：traditional crafts / handmade goods",3],

/* ---------------- 体育 sport ---------------- */
["tournament","/ˈtʊənəmənt/","n.","锦标赛","a series of matches leading to a winner","The tournament attracts teams from thirty countries.","这项锦标赛吸引了来自三十个国家的队伍。","sport","体育/比赛/国际","tourn(=turn 转/较量)+ament","championship; competition; contest","international tournament; knockout tournament; win a tournament","口语 Part2 描述体育赛事",2],
["referee","/ˌrefəˈriː/","n./v.","裁判；裁决","an official who controls a sports match","The referee awarded a penalty in the final minute.","裁判在最后一分钟判罚点球。","sport","体育/规则/比赛","refer(提交裁决)+ee(受动者)","umpire; official; judge","the referee; referee a match; match referee","口语 Part1 sports 可用",2],
["spectator","/spekˈteɪtə/","n.","观众","a person who watches an event","Thousands of spectators filled the stadium.","数千名观众挤满了体育场。","sport","体育/人群/活动","spect(=look 看)+ator","viewer; onlooker; audience","thousands of spectators; spectator sport; attract spectators","写作：spectator sports / live audience",2],
["endurance","/ɪnˈdjʊərəns/","n.","耐力","the ability to keep doing something difficult","Marathon training builds both speed and endurance.","马拉松训练同时提升速度与耐力。","sport","体育/健康/品质","en-(使)+dur(=hard 坚忍)+ance","stamina; staying power; resilience","physical endurance; build endurance; endurance training","写作：physical endurance / stamina",2],
["amateur","/ˈæmətə/","n./adj.","业余爱好者；业余的","someone who does something for pleasure, not money","The event is open to amateur runners.","这项赛事对业余跑者开放。","sport","体育/工作/身份","amat(=love 爱好)+eur","non-professional; hobbyist; enthusiast","amateur athlete; amateur player; amateur photographer","写作：amateur vs professional",2],
["athlete","/ˈæθliːt/","n.","运动员","a person trained in sports and physical exercise","Professional athletes train for six hours a day.","职业运动员每天训练六小时。","sport","体育/职业/健康","athl(=contest 竞赛)+ete","sportsman; competitor; player","professional athlete; elite athlete; train athletes","写作：professional sportsmen and women",1],
["sponsorship","/ˈspɒnsəʃɪp/","n.","赞助","financial support given by a company","Sponsorship deals fund most professional teams.","赞助协议资助了大多数职业球队。","sport","体育/商业/媒体","sponsor(担保人)+ship","funding; backing; patronage","corporate sponsorship; sponsorship deal; attract sponsorship","写作：commercial sponsorship / advertising",2],
["doping","/ˈdəʊpɪŋ/","n.","使用兴奋剂","the use of banned drugs to improve performance","Doping scandals damage the reputation of sport.","兴奋剂丑闻损害了体育的声誉。","sport","体育/道德/新闻","dope(麻醉剂)+ing","drug use; performance-enhancing drugs","doping scandal; doping test; anti-doping agency","写作体育道德话题：fair play",3],
["league","/liːɡ/","n.","联赛；联盟","a group of teams or countries joined together","The local league has expanded to twelve clubs.","当地联赛已扩军到十二家俱乐部。","sport","体育/组织/比赛","lig(=bind 绑)+ue","association; federation; competition","football league; league table; join a league","口语 Part1 sports 常用",2],
["stamina","/ˈstæmɪnə/","n.","耐力；持久力","the ability to sustain prolonged effort","Cycling long distances requires real stamina.","长距离骑行需要真正的耐力。","sport","体育/健康/能力","stamin(=thread 生命线)+a","endurance; staying power; resilience","build stamina; physical stamina; require stamina","写作：stamina and determination",3],

/* ---------------- 家庭 family ---------------- */
["household","/ˈhaʊshəʊld/","n./adj.","家庭；家务的","all the people living in one home","Single-parent households have become more common.","单亲家庭变得更加常见。","family","家庭/社会/数据","house(房屋)+hold(持有)","family; home; domestic unit","household income; one-parent household; household chores","图表题：household income / household size",2],
["upbringing","/ˈʌpbrɪŋɪŋ/","n.","养育；成长经历","the way a child is raised","A supportive upbringing shapes future confidence.","支持性的成长环境塑造未来的自信。","family","家庭/教育/成长","up+bring(抚养)+ing","nurture; rearing; raising","strict upbringing; supportive upbringing; childhood upbringing","写作：nature vs nurture",3],
["sibling","/ˈsɪblɪŋ/","n.","兄弟姐妹","a brother or sister","Only children often behave differently from those with siblings.","独生子女的行为常与有兄弟姐妹的孩子不同。","family","家庭/关系/社会","sib(=kin 亲属)+ling","brother or sister; kin","sibling rivalry; older sibling; have siblings","写作：sibling relationships / only child",2],
["nurture","/ˈnɜːtʃə/","v./n.","培养；养育","to care for and encourage growth","Schools should nurture creativity, not just exam skills.","学校应培养创造力，而不仅是应试技能。","family","家庭/教育/成长","nurt(=nourish 滋养)+ure","foster; raise; cultivate","nurture talent; nurture creativity; nature versus nurture","写作：nurture talent / nature vs nurture",3],
["kinship","/ˈkɪnʃɪp/","n.","亲属关系；亲近感","family relationship; a feeling of belonging","Kinship networks still support many rural families.","亲属网络仍在支撑许多农村家庭。","family","家庭/社会/人类学","kin(亲属)+ship","family ties; relationship; bond","kinship network; kinship ties; sense of kinship","写作：family bonds / close-knit communities",3],
["divorce","/dɪˈvɔːs/","n./v.","离婚","the legal ending of a marriage","The divorce rate has risen in many urban areas.","许多城市的离婚率上升了。","family","家庭/社会/法律","di-(分开)+vorce(=turn 转)","separation; split; dissolution","divorce rate; get a divorce; divorce proceedings","写作：divorce rate / family structure",2],
["parenting","/ˈpeərəntɪŋ/","n.","育儿；养育方式","the activity of raising children","Good parenting requires time, not just money.","好的育儿需要的是时间，而不只是金钱。","family","家庭/教育/社会","parent(父母)+ing","child-rearing; child care; upbringing","good parenting; parenting style; parenting skills","写作：parenting styles / parental involvement",2],
["adolescent","/ˌædəˈlesnt/","n./adj.","青少年；青春期的","a young person developing into an adult","Adolescents need more sleep than adults do.","青少年比成年人需要更多睡眠。","family","家庭/教育/健康","ad-(到)+olesc(=grow 成长)+ent","teenager; youth; juvenile","adolescent behaviour; adolescent years; during adolescence","写作：adolescents / young people 替换 teenagers",3],
["guardian","/ˈɡɑːdiən/","n.","监护人；守护者","someone who protects or has legal care of a child","The court appointed a guardian for the child.","法院为孩子指定了一名监护人。","family","家庭/法律/责任","guard(守卫)+ian","protector; custodian; carer","legal guardian; appoint a guardian; guardian of","写作：legal guardians / foster care",3],
["domestic","/dəˈmestɪk/","adj.","家庭的；国内的","relating to the home or to one's own country","Domestic duties are still unevenly shared.","家务分工仍然不均。","family","家庭/社会/经济","dom(=house 家)+estic","household; home; national","domestic chores; domestic violence; domestic market","写作：domestic responsibilities / household tasks",2],

/* ---------------- 食物 food ---------------- */
["nutrition","/njuˈtrɪʃn/","n.","营养","the process of getting the food needed for health","Schools should teach basic nutrition.","学校应教授基础营养知识。","food","食物/健康/教育","nutri(=nourish 滋养)+tion","nourishment; diet; sustenance","good nutrition; nutrition education; poor nutrition","写作：balanced nutrition / nutritional value",2],
["cuisine","/kwɪˈziːn/","n.","菜系；烹饪","a style of cooking","Italian cuisine is popular worldwide.","意大利菜在全世界都很受欢迎。","food","食物/文化/旅游","cuis(=cook 烹饪)+ine","cooking; food style; gastronomy","local cuisine; traditional cuisine; French cuisine","口语 Part1 food 高频替换词",2],
["ingredient","/ɪnˈɡriːdiənt/","n.","原料；成分","one of the foods used to make a dish","Fresh ingredients make a real difference.","新鲜的原料会带来真正的差别。","food","食物/烹饪/健康","in-(进入)+gred(=step 走)+ient","component; element; constituent","fresh ingredients; key ingredient; natural ingredients","口语 Part1/写作：ingredients and recipes",2],
["organic","/ɔːˈɡænɪk/","adj.","有机的；不使用农药的","produced without artificial chemicals","Organic food is often more expensive.","有机食品通常更贵。","food","食物/农业/健康","organ(器官/生命体)+ic","natural; chemical-free; bio","organic food; organic farming; organic produce","写作：organic farming / intensive farming 对比",2],
["beverage","/ˈbevərɪdʒ/","n.","饮料","any drink other than water","Sugary beverages are linked to obesity.","含糖饮料与肥胖有关。","food","食物/健康/商业","bev(=drink 喝)+erage","drink; refreshment","sugary beverages; alcoholic beverage; beverage industry","写作：sugar-sweetened beverages",3],
["preservative","/prɪˈzɜːvətɪv/","n.","防腐剂","a substance used to keep food fresh longer","Many preservatives extend shelf life but reduce quality.","许多防腐剂延长了保质期却降低了品质。","food","食物/健康/工业","pre-(预先)+serv(=keep 保存)+ative","additive; stabiliser; chemical","food preservatives; artificial preservatives; without preservatives","写作：artificial additives / processed food",3],
["calorie","/ˈkæləri/","n.","卡路里","a unit measuring the energy in food","Fast food meals often contain over a thousand calories.","快餐餐食常常含有一千卡路里以上。","food","食物/健康/数据","calor(=heat 热)+ie","energy unit; kilocalorie","calorie intake; low-calorie; count calories","写作：calorie intake / high-calorie diet",2],
["staple","/ˈsteɪpl/","n./adj.","主食；主要的","a basic food eaten regularly; most important","Rice is a staple for more than half the world.","稻米是世界一半以上人口的主食。","food","食物/文化/经济","源自中世纪英语，原指主要商品","basic food; main crop; principal item","staple food; staple diet; staple crop","写作：staple food / staple diet",3],
["vegetarian","/ˌvedʒəˈteəriən/","n./adj.","素食者；素食的","a person who does not eat meat","A vegetarian diet can lower health risks.","素食饮食可以降低健康风险。","food","食物/健康/环境","veget(=plant 植物)+arian","plant-eater; vegan; meat-free","vegetarian diet; become vegetarian; vegetarian option","写作：vegetarianism / plant-based diet",2],
["malnutrition","/ˌmælnjuˈtrɪʃn/","n.","营养不良","poor health caused by a bad diet","Malnutrition remains a serious problem in poor regions.","在贫困地区，营养不良仍是严重问题。","food","食物/健康/社会","mal-(坏)+nutrition(营养)","undernourishment; poor diet; deficiency","suffer from malnutrition; child malnutrition; rates of malnutrition","写作：malnutrition / food insecurity",3]
];
